name: TicTacToe CI-CD

on: workflow_dispatch

jobs: 
  pre-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tictactoe
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          sparse-checkout: tictactoe
      - name: Setup NodeJs
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'
      - name: Install Dependencies
        run: npm ci
      - name: Lint Code
        run: npm run lint
      - name: Test Code
        run: npm run test

  build:
    runs-on: ubuntu-latest
    needs: pre-build
    defaults:
      run:
        working-directory: tictactoe
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          sparse-checkout: tictactoe
      - name: Setup NodeJs
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'
      - name: Install Dependencies
        run: npm ci
      - name: Build Code
        run: npm run build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tictactoe
          path: tictactoe/dist/

  docker:
    runs-on: ubuntu-latest
    needs: 
      - pre-build
      - build
    defaults:
      run:
        working-directory: tictactoe
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          sparse-checkout: tictactoe
      - name: Setup Docker
        uses: docker/setup-buildx-action@v3
      - name: Docker Build
        run: docker build -t tictactoe:latest .
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker Push
        run: docker push "${{ vars.DOCKERHUB_USERNAME }}/tictactoe:latest"